objects/BMCServiceDesk__Incident__c.object
<CustomObject>
    <customHelpPage>BMCServiceDesk__StdFormHelpIncident</customHelpPage>
    <description>This object allows you to store data for incidents.</description>
    <fields>
        <fullName>BMCServiceDesk__EmailServiceAddress__c</fullName>
        <description>This field stores the email service address, which is used to create an incident record.</description>
        <label>Email Service Address</label>
        <length>512</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>From the list of options, select the incident&apos;s category. Categories allow you to classify the incident using standard classifications, which can be easily tracked for reporting purposes.</inlineHelpText>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BMCServiceDesk__Category__c.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>BMCServiceDesk__Category__c.BMCServiceDesk__AvailableForIncidents__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Select an active category for the incident/ service request.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>BMCServiceDesk__Category__c</referenceTo>
        <relationshipLabel>Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is automatically set to the Client ID of the client who submitted the incident.</inlineHelpText>
        <label>Client ID</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.BMCServiceDesk__FKAccount__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>User.BMCServiceDesk__Account__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.BMCServiceDesk__FKAccount__c</field>
                <operation>equals</operation>
                <valueField>User.Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Incidents3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKIncident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>BMCServiceDesk__Incident__c</referenceTo>
        <relationshipLabel>Linked Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>From the list of options, select the appropriate status for the incident. Status is used to display the progress of an incident through its stages of opening to closure.</inlineHelpText>
        <label>Status</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Select an active status that applies to incidents.</errorMessage>
            <filterItems>
                <field>BMCServiceDesk__Status__c.BMCServiceDesk__appliesToIncident__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>BMCServiceDesk__Status__c.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BMCServiceDesk__Status__c</referenceTo>
        <relationshipLabel>Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKUrgency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>From the list of options, select how quickly the incident needs to be resolved. The urgency and the level of impact are used to calculate the priority of the incident.</inlineHelpText>
        <label>Urgency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BMCServiceDesk__Urgency__c.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>Select an active urgency.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>BMCServiceDesk__Urgency__c</referenceTo>
        <relationshipLabel>Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this field if the incident record is no longer valid, but the record has to be retained for compliance with the records retention policy. For example, if a client has left the account, all the client&apos;s incident records would be invalid.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__incidentDescription__c</fullName>
        <inlineHelpText>Use this field to enter a description of the issue the client is reporting.</inlineHelpText>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__openDateTime__c</fullName>
        <inlineHelpText>This field is automatically set to the date and time at which the incident was created.</inlineHelpText>
        <label>Opened Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__state__c</fullName>
        <defaultValue>true</defaultValue>
        <label>State Open</label>
        <type>Checkbox</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BMCServiceDesk__IncidentHistory__c.object
<CustomObject>
    <customHelpPage>BMCServiceDesk__StdFormHelpIncidentHistory</customHelpPage>
    <description>This object allows you to store data that tracks the history of all actions that have been performed on incidents.</description>
    <fields>
        <fullName>BMCServiceDesk__FKIncident__c</fullName>
        <label>Incident</label>
        <referenceTo>BMCServiceDesk__Incident__c</referenceTo>
        <relationshipLabel>Action History</relationshipLabel>
        <relationshipName>Incident_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this field if the incident record is no longer valid, but the record has to be retained for compliance with the records retention policy.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <label>Incident History</label>
    <nameField>
        <label>Incident History ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incident History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BMCServiceDesk__Task__c.object
<CustomObject>
    <customHelpPage>BMCServiceDesk__StdFormHelpTask</customHelpPage>
    <description>This object allows you to store data for tasks.</description>
    <fields>
        <fullName>BMCServiceDesk__FKCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>From the list of options, select the task&apos;s category. Categories allow you to classify the task using standard classifications, which can be easily tracked for reporting purposes.</inlineHelpText>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BMCServiceDesk__Category__c.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>Select an active category.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>BMCServiceDesk__Category__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is automatically set to the Client ID of the client who submitted the task.</inlineHelpText>
        <label>Client ID</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKIncident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BMCServiceDesk__Incident__c.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>Select an active incident.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>BMCServiceDesk__Incident__c</referenceTo>
        <relationshipLabel>Linked Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>From the list of options, select the appropriate status for the task. Status is used to display the progress of a task through its stages of opening to closure.</inlineHelpText>
        <label>Status</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Select an active status that applies to tasks.</errorMessage>
            <filterItems>
                <field>BMCServiceDesk__Status__c.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>BMCServiceDesk__Status__c.BMCServiceDesk__appliesToTask__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BMCServiceDesk__Status__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKUrgency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>From the list of options, select how quickly the task needs to be completed. The urgency and the level of impact are used to calculate the priority of the task.</inlineHelpText>
        <label>Urgency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BMCServiceDesk__Urgency__c.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>Select an active urgency.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>BMCServiceDesk__Urgency__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this field if the task record is no longer valid, but the record has to be retained for compliance with the records retention policy. For example, if a client has left the account, all tasks associated with the client would be invalid.</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__openDateTime__c</fullName>
        <inlineHelpText>This field is automatically set to the date and time at which the task was created.</inlineHelpText>
        <label>Opened Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__state__c</fullName>
        <defaultValue>true</defaultValue>
        <label>State Open</label>
        <type>Checkbox</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Cloudaction_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Setting_Name__c</fullName>
        <label>Setting_Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Setting_Value__c</fullName>
        <label>Setting Value</label>
        <type>TextArea</type>
    </fields>
    <label>Cloudaction Settings</label>
</CustomObject>

classes/Test_DoED_Update_IMRNum_IMRDesc_Status.cls
@IsTest
Private class Test_DoED_Update_IMRNum_IMRDesc_Status
{
    static testMethod void validateIncidentQueue()
    {
        
        String userName = UserInfo.getUserName();
        User activeUser = [Select Id, Name, Email From User where Username = : userName limit 1];
        String userNm = activeUser.Name;
        
        String userId = activeUser.Id;

         //Create Urgency
        BMCServiceDesk__Urgency__c urgency = new BMCServiceDesk__Urgency__c(Name = 'Test_sbti_HIGH');
        insert urgency;
        
        //Create Category
        BMCServiceDesk__Category__c cat = new BMCServiceDesk__Category__c(BMCServiceDesk__FKUrgency__c = urgency.Id, Name = 'Test_sbti_New Category', BMCServiceDesk__AvailableForIncidents__c=true);
        insert cat;
        
        //Create Status
        BMCServiceDesk__Status__c status1 = new BMCServiceDesk__Status__c(
                                            Name = 'SUBMITTED_1',  
                                            BMCServiceDesk__appliesToTask__c = true,
                                            
                                            BMCServiceDesk__state__c=true);
        insert status1;
        
         //Create Status
        BMCServiceDesk__Status__c status2 = new BMCServiceDesk__Status__c(
                                            Name = 'SUBMITTED_2',  
                                           
                                            BMCServiceDesk__appliesToIncident__c = true,
                                            BMCServiceDesk__state__c=true);
        insert status2;
        
        //Create Status
        BMCServiceDesk__Status__c ca_email_sent_status = new BMCServiceDesk__Status__c(
                                            Name = 'Email Sent',  
                                           
                                            BMCServiceDesk__appliesToIncident__c = true,
                                            BMCServiceDesk__state__c=true);
        insert ca_email_sent_status;
        
        //Create Status
        BMCServiceDesk__Status__c ca_email_received_status = new BMCServiceDesk__Status__c(
                                            Name = 'Email Received',  
                                           
                                            BMCServiceDesk__appliesToIncident__c = true,
                                            BMCServiceDesk__state__c=true);
        insert ca_email_received_status;
        
        Cloudaction_Settings__c ab1 = new Cloudaction_Settings__c(Name='BMCServiceDesk__FKCategory__c', Description__c ='ca_email_sent_status', Detail__c ='ca_email_sent_status', Setting_Name__c='ca_email_sent_status', Setting_Value__c=ca_email_sent_status.id);
        insert ab1;
        
        Cloudaction_Settings__c ab2 = new Cloudaction_Settings__c(Name='BMCServiceDesk__FKCategory__c1', Description__c ='ca_email_received_status', Detail__c ='ca_email_received_status', Setting_Name__c='ca_email_received_status', Setting_Value__c=ca_email_received_status.id);
        insert ab2;
        
        Test.startTest();
         //Create Incident
        BMCServiceDesk__Incident__c oInci = new BMCServiceDesk__Incident__c( BMCServiceDesk__incidentDescription__c = 'Test_sbti_IncidentControllerTest', 
                BMCServiceDesk__FKClient__c = userId ,
                BMCServiceDesk__FKCategory__c = cat.Id,
                BMCServiceDesk__openDateTime__c = System.now(), 
                BMCServiceDesk__FKStatus__c = status2.Id,
                BMCServiceDesk__State__c=true
                );
        insert oInci;
        
        //Create task
        BMCServiceDesk__Task__c oInc = new BMCServiceDesk__Task__c( //BMCServiceDesk__incidentDescription__c = 'Test_sbti_IncidentControllerTest', 
                BMCServiceDesk__FKClient__c = userId ,
                //BMCServiceDesk__FKCategory__c = cat.Id,
                //BMCServiceDesk__openDateTime__c = System.now(),
                BMCServiceDesk__FKIncident__c = oInci.Id, 
                BMCServiceDesk__FKStatus__c = status1.Id,
                BMCServiceDesk__State__c=true
                //BMCServiceDesk__EmailServiceAddress__c = userEmail1
                );
        insert oInc;
        
        //System.assertNotEquals(null, oInc.Owner);
        //System.assertNotEquals(null, oInc1.Owner);
        
        //Create Action
        BMCServiceDesk__Action__c action = new BMCServiceDesk__Action__c(
                                            Name = 'Email Received',  
                                            BMCServiceDesk__appliesToIncident__c = true,
                                            BMCServiceDesk__inactive__c = false);
        insert action;
        
        String history_description = 'Email Received-Re: Sandbox: Task##' + oInc.Name + '## has been opened and assigned to test 1 Edcaps (Ref:IN:' + oInci.Name + ')';
        
        String notes_data = 'From:gbsai6@gmail.com To:edcaps.reply.sandbox@outlook.com; Cc:Subject:Re: Sandbox: Task##00000286## has been opened and assigned to test 1 Edcaps (Ref:IN:00000576)On Tue, Jan 14, 2014 at 7:20 PM, EDCAPS Reply Sandbox <edcaps.reply.sandbox@outlook.com> wrote:';
        notes_data = notes_data + '> IMR Number##700000##' + '> IMR Description##IMR DESCRIPTION GOES HERE##> Task Update##IN PROGRESS## Resolution##RESOLUTION GOES HERE##';
        
        //create incident history
        BMCServiceDesk__IncidentHistory__c oInc1 = new BMCServiceDesk__IncidentHistory__c( 
                BMCServiceDesk__FKAction__c = action.Id,
                BMCServiceDesk__description__c = history_description,
                BMCServiceDesk__note__c = notes_data,
                BMCServiceDesk__EmailConversationData__c = 'From:bala.gopalakrishnan@sbti.com#@#@#@#To:sbtihelpdesk@outlook.com; #@#@#@#Cc:',
                BMCServiceDesk__FKIncident__c = oInci.Id,
                BMCServiceDesk__FKUser__c = userId
               
                );
        insert oInc1;
        
        String history_description1 = 'Email Received-Re: Sandbox: Task##' + oInc.Name + '## has been opened and assigned to test 1 Edcaps (Ref:IN:' + oInci.Name + ')';
        String history_description2 = 'Email Received-Re: Sandbox: ' + oInc.Name + '## has been opened and assigned to test 1 Edcaps (Ref:IN:' + oInci.Name + ')';

                
        String notes_data1 = 'From:gbsai6@gmail.com To:edcaps.reply.sandbox@outlook.com; Cc:Subject:Re: Sandbox: Task##00000286## has been opened and assigned to test 1 Edcaps (Ref:IN:00000576)On Tue, Jan 14, 2014 at 7:20 PM, EDCAPS Reply Sandbox <edcaps.reply.sandbox@outlook.com> wrote:';
        notes_data1 = notes_data1 + '> IMR Number##900000##' + '> IMR Description##IMR DESCRIPTION GOES HERE##> Task Update##CLOSED## Resolution##RESOLUTION GOES HERE##';
        
        //create incident history
        BMCServiceDesk__IncidentHistory__c oInc2 = new BMCServiceDesk__IncidentHistory__c( 
                BMCServiceDesk__FKAction__c = action.Id,
                BMCServiceDesk__description__c = history_description1,
                BMCServiceDesk__note__c = notes_data1,
                BMCServiceDesk__EmailConversationData__c = 'From:bala.gopalakrishnan@sbti.com#@#@#@#To:sbtihelpdesk@outlook.com; #@#@#@#Cc:',
                BMCServiceDesk__FKIncident__c = oInci.Id,
                BMCServiceDesk__FKUser__c = userId
               
                );
        insert oInc2;
        
        //create incident history
        BMCServiceDesk__IncidentHistory__c oInc3 = new BMCServiceDesk__IncidentHistory__c( 
                BMCServiceDesk__FKAction__c = action.Id,
                BMCServiceDesk__description__c = history_description2,
                BMCServiceDesk__note__c = notes_data1,
                BMCServiceDesk__EmailConversationData__c = 'From:bala.gopalakrishnan@sbti.com#@#@#@#To:sbtihelpdesk@outlook.com; #@#@#@#Cc:',
                BMCServiceDesk__FKIncident__c = oInci.Id,
                BMCServiceDesk__FKUser__c = userId
               
                );
        insert oInc3;
        
        Date a = null;
        Date b = null;
        
        String abc1 = CalculateBusinessTimeElapsed.calculateBusinessHMS(a,b);
        Long bc1 = CalculateBusinessTimeElapsed.calculateBusinessSeconds(a,b);
        Long cd1 = CalculateBusinessTimeElapsed.calculateBusinessHours(a,b);
        
        String abc = CalculateBusinessTimeElapsed.calculateBusinessHMS(System.now(),System.now());
        Long bc = CalculateBusinessTimeElapsed.calculateBusinessSeconds(System.now(),System.now());
        Long cd = CalculateBusinessTimeElapsed.calculateBusinessHours(System.now(),System.now());
        
        //delete oInc;     
        Test.stopTest();
    }    
}