objects/BMCServiceDesk__Incident__c.object
<CustomObject>
    <customHelpPage>BMCServiceDesk__StdFormHelpIncident</customHelpPage>
    <description>This object allows you to store data for incidents.</description>
    <fields>
        <fullName>BMCServiceDesk__FKCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>From the list of options, select the incident&apos;s category. Categories allow you to classify the incident using standard classifications, which can be easily tracked for reporting purposes.</inlineHelpText>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BMCServiceDesk__Category__c.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>BMCServiceDesk__Category__c.BMCServiceDesk__AvailableForIncidents__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Select an active category for the incident/ service request.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>BMCServiceDesk__Category__c</referenceTo>
        <relationshipLabel>Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is automatically set to the Client ID of the client who submitted the incident.</inlineHelpText>
        <label>Client ID</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.BMCServiceDesk__FKAccount__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>User.BMCServiceDesk__Account__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.BMCServiceDesk__FKAccount__c</field>
                <operation>equals</operation>
                <valueField>User.Contact.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Incidents3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKIncident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <referenceTo>BMCServiceDesk__Incident__c</referenceTo>
        <relationshipLabel>Linked Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ITP_IMRDesc__c</fullName>
        <label>ITP_IMRDesc</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ITP_IMRNum__c</fullName>
        <label>ITP_IMRNum</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ITP_TaskUpdate__c</fullName>
        <label>ITP_TaskUpdate</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BMCServiceDesk__Task__c.object
<CustomObject>
    <customHelpPage>BMCServiceDesk__StdFormHelpTask</customHelpPage>
    <description>This object allows you to store data for tasks.</description>
    <fields>
        <fullName>BMCServiceDesk__FKCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>From the list of options, select the task&apos;s category. Categories allow you to classify the task using standard classifications, which can be easily tracked for reporting purposes.</inlineHelpText>
        <label>Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BMCServiceDesk__Category__c.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>Select an active category.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>BMCServiceDesk__Category__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKClient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is automatically set to the Client ID of the client who submitted the task.</inlineHelpText>
        <label>Client ID</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BMCServiceDesk__FKIncident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>BMCServiceDesk__Incident__c.BMCServiceDesk__inactive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>Select an active incident.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>BMCServiceDesk__Incident__c</referenceTo>
        <relationshipLabel>Linked Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Task #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ITP_UpdateRelatedTaskTestClass.cls
@isTest 
private class ITP_UpdateRelatedTaskTestClass {
    static testMethod void validateITP_UpdateRelatedTask() {

  test.StartTest();
    List<User> usr = [SELECT Id FROM User];
   
        BMCServiceDesk__Status__c status = new BMCServiceDesk__Status__c (
        BMCServiceDesk__appliesToTask__c = true,
        Name = 'MYSTATUS');
        insert status;
        
        
        BMCServiceDesk__Category__c cat = new BMCServiceDesk__Category__c (
        Name = 'TSTCAT',
        BMCServiceDesk__AvailableForServiceCatalog__c = true,
        BMCServiceDesk__AvailableForIncidents__c = true);
        insert cat;

          User CurrentUser=New User();
         CurrentUser=[select Id,Name from User where Id=: userinfo.getuserId()];

    
       BMCServiceDesk__Incident__c inc = new BMCServiceDesk__Incident__c (
       BMCServiceDesk__FKCategory__c = cat.Id,
       BMCServiceDesk__FKClient__c = CurrentUser.Id,
       ITP_IMRNum__C = Null,      
       ITP_TaskUpdate__c =Null
       );
       insert inc;
        
       BMCServiceDesk__Task__c tsk = new BMCServiceDesk__Task__c (
       BMCServiceDesk__FKClient__c = usr[0].Id,
       BMCServiceDesk__FKIncident__c = inc.Id);
       insert tsk;
        
       inc.ITP_TaskUpdate__c = 'MYSTATUS';       
       inc.ITP_IMRNum__C = '12345';
       inc.ITP_IMRDesc__c = 'My Description';

     
       
       update inc;
       test.StopTest();

    }
}